### ISSUE TITLE
Push Metrics via Sumocollector

### ISSUE THREAD

**Issue by krx252525** [SumoLogic/sumologic-prometheus-scraper#2]
@frankreno will this tool eventually stream logs in one of the [supported formats](https://help.sumologic.com/Metrics/Metrics-Sources)? Our log ingress is at a premium whereas we have spare DPM for metrics ingress. Happy to provide a PR if I'm not overlooking something obvious?

**Comment by frankreno** [comment]
@keir-rex : it’s already in the works :) new metrics collection for k8s will be available in the coming weeks and this tool is at the heart of it.

**Comment by frankreno** [comment]
pinged you on slack for more details on what you are looking for, let's continue the chat there and revisit this issue.

**Comment by frankreno** [comment]
closing as k8s use is coming and will be tracked separately...
